spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    validate-on-migrate: true

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    br.ufpr.sept.so2: INFO
